name: Tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Run tests
        run: |
          gem install bundler -v 2.2.7
          bundle install
          bundle exec rake
